### ISSUE TITLE
Problem z systemem ników

### ISSUE THREAD

**Issue by Myszka30** [Myszka30/launcher#1]
Gdy odpalisz kilka razy instalator w pliku username.txt gromadzą się nazwy w kolejnych linijkach

![image-2.png](https://github.com/Myszka30/launcher/assets/87234858/85894a9c-fa3b-412c-8d25-efc7e336286a)

**Comment by Bbolken1q** [comment]
1. Nicków
2. Fixed (Usuwa plik za każdym razem)

**Comment by Bbolken1q** [comment]
Push zaraz
